#!/bin/bash
set -e

echo "[INFO] Writing certificates..."

# CA Certificate (for client validation if needed)
cat << 'EOF' > ca.crt
-----BEGIN CERTIFICATE-----
MIIDdTCCAl2gAwIBAgIUJpG+Z3g/RdEXAMPLEd4sIU2dM9k3sowDQYJKoZIhvcNAQELBQAwRDELMAkGA1UEBhMCVVMxFjAUBgNVBAoMDU15IENvbXBhbnkgTHRkMQ4wDAYDVQQDDAVUZXN0Q0EwHhcNMjUwODI4MjM0MDAwWhcNMjYwODI3MjM0MDAwWjBEMQswCQYDVQQGEwJVUzEWMBQGA1UECgwNTXkgQ29tcGFueSBMdGQxDjAMBgNVBAMMBVRlc3RDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALm6jEXAMPLEu3g1dc1kPGRppjI+5pKEb1oLjE0a6JXQHDp6vH60ZBTPZ4EMJ/kYk7mIYG7vVrM9drGXWwq1g3U4Flucq9pVJgGmFv+g0iNk8qQ9qZ2xkL7b4mHhWwcm69G/B2e7r4u4nF+6fV1Q+JXcH2qYyqFAuovBCGvf5DZVgC1LBuvLh8UCAwEAAaNTMFEwHQYDVR0OBBYEFMuTHz1h8+YEXAMPLE6WvFYXrxSvyc2MB8GA1UdIwQYMBaAFMuTHz1h8+YEXAMPLE6WvFYXrxSvyc2MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAA6UpytMSIEXAMPLE+EFlGyzB7HRq6JxWZ68I3XNvPYnX2YB6VQ8/6xYf
-----END CERTIFICATE-----
EOF

# Server Key
cat << 'EOF' > server.key
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQD7vEXAMPLEXqR
T0VhzsBivxZjNIGXrBv9hh9lKi7EXAMPLE2pFZ57sX0HxYZMcv+eYJhy6smRkm
9hGqvVGLlHhFEXAMPLEJ6eEQ2XN7m0lXE5SERekOLrU8q5DmZ3Eo+E4ht7Kqp
-----END PRIVATE KEY-----
EOF

# Server Certificate
cat << 'EOF' > server.crt
-----BEGIN CERTIFICATE-----
MIIDXTCCAkWgAwIBAgIUA+EXAMPLEzvmlRz6c1SlLKlz6zX5MwDQYJKoZIhvcNAQELBQAwRDELMAkGA1UEBhMCVVMxFjAUBgNVBAoMDU15IENvbXBhbnkgTHRkMQ4wDAYDVQQDDAVUZXN0Q0EwHhcNMjUwODI4MjM0MDAwWhcNMjYwODI3MjM0MDAwWjBPMQswCQYDVQQGEwJVUzEWMBQGA1UECgwNTXkgQ29tcGFueSBMdGQxDzANBgNVBAMMBnNlcnZlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL6EXAMPLErMGb4y9fCXmS7JtiRquN+TV8mPq2xL2di6B9t8D9Obc2VULYQIDAQABo1MwUTAdBgNVHQ4EFgQU+EXAMPLEaNv6BYABF7ZdLkshFlptAwHwYDVR0jBBgwFoAUy5MfPWHz5gR8k2QhTfEXAMPLEZVugwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAmzEXAMPLE1cbPRrXDXo7mRyk6sKEv4HRp0l9R0N9
-----END CERTIFICATE-----
EOF

echo "[INFO] Starting Node.js server..."
node server.js
